// Generated by dts-bundle-generator v9.5.1

declare const app: import("elysia").default<"", false, {
	decorator: {
		db: import("bun:sqlite").Database;
	};
	store: {};
	derive: {};
	resolve: {};
}, {
	type: {};
	error: {};
}, {
	schema: {};
	macro: {};
}, {
	feed: {
		properties: {
			post: {
				body: {
					page: number;
				};
				params: Record<never, string>;
				query: unknown;
				headers: unknown;
				response: {
					200: {
						status: "success";
						payload: {
							properties: {
								id: number;
								sourceURL: string;
								title: string;
								cityName: string;
								price: number | null;
								area: number | null;
								previewImageURL: string;
							}[];
							hasMore: boolean;
						};
					};
				} | {
					200: {
						status: "error";
						message: string;
					};
				};
			};
		};
	};
} & {
	commute: {
		durations: {
			get: {
				body: unknown;
				params: Record<never, string>;
				query: {
					userSessionId: string;
				};
				headers: unknown;
				response: {
					200: {
						status: "success";
						payload: {
							durations: {
								[x: string]: {
									id: string;
									walking: number | null;
									driving: number | null;
									transit: number | null;
									biking: number | null;
									addressLabel: string;
								};
							};
							preferences: {
								addresses: {
									id: string;
									label: string;
								}[];
								maxDurations: {
									walking: number | null;
									driving: number | null;
									transit: number | null;
									biking: number | null;
								};
							};
						};
					};
				} | {
					200: {
						status: "error";
						message: string;
					};
				};
			};
		};
	} & {
		preferences: {
			get: {
				body: unknown;
				params: Record<never, string>;
				query: {
					userSessionId: string;
				};
				headers: unknown;
				response: {
					200: {
						status: "success";
						payload: {
							preferences: {
								addresses: {
									id: string;
									label: string;
								}[];
								maxDurations: {
									walking: number | null;
									driving: number | null;
									transit: number | null;
									biking: number | null;
								};
							};
						};
					};
				} | {
					200: {
						status: "error";
						message: string;
					};
				};
			};
		};
	} & {
		preferences: {
			post: {
				body: {
					preferences: {
						addresses: {
							id: string;
							label: string;
						}[];
						maxDurations: {
							walking: number | null;
							driving: number | null;
							transit: number | null;
							biking: number | null;
						};
					};
					userSessionId: string;
				};
				params: Record<never, string>;
				query: unknown;
				headers: unknown;
				response: {
					200: {
						status: "success";
						payload: {
							preferences: {
								addresses: {
									id: string;
									label: string;
								}[];
								maxDurations: {
									walking: number | null;
									driving: number | null;
									transit: number | null;
									biking: number | null;
								};
							};
						};
					};
				} | {
					200: {
						status: "error";
						message: string;
					};
				};
			};
		};
	};
}, {
	derive: {};
	resolve: {};
	schema: {};
}, {
	derive: {};
	resolve: {};
	schema: {};
}>;

export {
	app as default,
};

export {};
